---
- hosts: minecraft
  user: root
  vars_files:
    - variables.yml
  tasks:
    - command: chdir=/opt/msm tar -cvf {{ backup_file }} servers/
    - command: chdir=/opt/msm s3cmd put {{ backup_file }} {{ s3bucket }}

- hosts: local
  connection: local
  gather_facts: False
  tasks:
      - name: Stop Droplet
        digital_ocean: >
            state=absent
            command=droplet
            size_id=64
            region_id=1
            image_id=10581649
            ssh_key_ids=14937
            name=minecraft
            unique_name=yes
            wait_timeout=500
