---
- hosts: local
  connection: local
  gather_facts: False
  tasks:
      - name: Start Droplet
        digital_ocean: >
            state=present
            command=droplet
            size_id=64
            region_id=1
            image_id=10581649
            ssh_key_ids=14937
            name=minecraft
            unique_name=yes
            wait_timeout=500
        register: minecraft
      - name: Add to hosts list
        add_host: hostname={{ minecraft.droplet.ip_address }} groupname=minecraft


- hosts: minecraft
  user: root
  vars_files:
    - variables.yml
  tasks:
    - name: waiting for vm to come up
      wait_for: host=minecraft port=22 delay=60
    - name: S3 CMD
      apt: name=s3cmd state=present update_cache=yes
    - name: Ubuntu Firewall
      apt: name=ufw state=present
    - name: Java
      apt: name=openjdk-7-jre state=present
    - action: copy src=~/.s3cfg dest=/root/.s3cfg
    - command: mkdir -m 777 -p /opt/msm/servers creates=/opt/msm/server
    - command: s3cmd get {{ s3bucket }}/{{ backup_file }} /opt/msm/ creates=/opt/msm/{{ backup_file }}
    - command: tar -xvf {{ backup_file }} chdir=/opt/msm
    - ufw: state=enabled policy=allow
    - ufw: rule=allow port=22 proto=tcp
    - ufw: rule=allow port=25565 proto=tcp
    - get_url: url={{ msm_installer }} dest=/tmp/msm mode=u+x
    - command: /tmp/msm
    - command: msm jargroup changeurl minecraft {{ minecraft_jar }}
    - command: msm jargroup getlatest minecraft
    - command: msm {{ msm_server_name }} jar minecraft
    - command: msm {{ msm_server_name }} start
