---
- hosts: local
  connection: local
  gather_facts: False
  tasks:
      - name: Start Droplet
        digital_ocean: >
            state=present
            command=droplet
            size_id=64
            region_id=1
            image_id=10581649
            ssh_key_ids=14937
            name=minecraft
            unique_name=yes
            wait_timeout=500
        register: minecraft
      - name: Add to hosts list
        add_host: hostname={{ minecraft.droplet.ip_address }} groupname=minecraft

- hosts: minecraft
  user: root
  vars:
    - s3bucket: s3://jduck-minecraft-backup
  tasks:
    - name: S3 CMD
      apt: name=s3cmd state=present update_cache=yes
    - name: Ubuntu Firewall
      apt: name=ufw state=present
    - name: Java
      apt: name=openjdk-7-jre state=present
    - action: copy src=~/.s3cfg dest=/root/.s3cfg
    - action: command mkdir -m 777 -p /opt/msm/servers
    - action: command s3cmd sync {{ s3bucket }} /opt/msm/servers
    - ufw: state=enabled policy=allow
    - ufw: rule=allow port=22 proto=tcp
    - ufw: rule=allow port=25565 proto=tcp
    - get_url: url=https://raw.githubusercontent.com/jduckles/minecraft-server-manager/master/installers/debian.sh dest=/tmp/msm
    - action: command bash /tmp/msm
    - action: command msm jargroup changeurl minecraft https://s3.amazonaws.com/Minecraft.Download/versions/1.8.3/minecraft_server.1.8.3.jar
    - action: command msm jargroup getlatest minecraft
    - action: command msm micah-ship jar minecraft
    - action: command msm micah-ship start
